//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFinancialCrmm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankProcesses
    {
        public int BankProccesId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string ProcessType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> BankId { get; set; }
    
        public virtual Banks Banks { get; set; }
    }
}
