//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFinancialCrmm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spendings
    {
        public int SpendingId { get; set; }
        public string SpendingTitle { get; set; }
        public Nullable<decimal> SpendingAmount { get; set; }
        public Nullable<System.DateTime> SpendingDate { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
